# Generated by Django 4.2.4 on 2023-10-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_alter_agregarpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregarpost',
            name='fechaPublicacion',
            field=models.DateTimeField(),
        ),
    ]
